package java_fundamentals.lambdas_11;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.function.Supplier;

// GenomicsInstrument interface representing a genomics instrument
interface GenomicsInstrument {
    String getSequence();
}

// Example class implementing the GenomicsInstrument interface
class DNASequencer implements GenomicsInstrument {
    private String sequence;

    public DNASequencer(String sequence) {
        this.sequence = sequence;
    }

    @Override
    public String getSequence() {
        return sequence;
    }
}

public class HighThroughputGenomicsExample {
    public static void main(String[] args) {
        // Define a supplier to generate random DNA sequences
        Supplier<String> dnaSequenceSupplier = () -> {
            StringBuilder dnaSequenceBuilder = new StringBuilder();
            for (int i = 0; i < 100; i++) {
                int nucleotideIndex = (int) (Math.random() * 4);
                char nucleotide;
                switch (nucleotideIndex) {
                    case 0:
                        nucleotide = 'A';
                        break;
                    case 1:
                        nucleotide = 'T';
                        break;
                    case 2:
                        nucleotide = 'G';
                        break;
                    default:
                        nucleotide = 'C';
                }
                dnaSequenceBuilder.append(nucleotide);
            }
            return dnaSequenceBuilder.toString();
        };

        // Create a list of DNA sequencers representing DNA sequences generated by the supplier
        List<DNASequencer> dnaSequencers = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            dnaSequencers.add(new DNASequencer(dnaSequenceSupplier.get()));
        }

        // Define a predicate to filter DNA sequences containing 'ATG' sequence
        Predicate<DNASequencer> atgSequenceFilter = dnaSequencer -> dnaSequencer.getSequence().contains("ATG");

        // Define a function to convert DNA sequences to RNA sequences
        Function<DNASequencer, String> dnaToRnaConverter = dnaSequencer -> {
            String dnaSequence = dnaSequencer.getSequence();
            StringBuilder rnaSequenceBuilder = new StringBuilder();
            for (char nucleotide : dnaSequence.toCharArray()) {
                switch (nucleotide) {
                    case 'A':
                        rnaSequenceBuilder.append('U');
                        break;
                    case 'T':
                        rnaSequenceBuilder.append('A');
                        break;
                    case 'G':
                        rnaSequenceBuilder.append('C');
                        break;
                    case 'C':
                        rnaSequenceBuilder.append('G');
                        break;
                }
            }
            return rnaSequenceBuilder.toString();
        };

        // Define a consumer to print DNA sequences
        Consumer<DNASequencer> dnaSequencePrinter = dnaSequencer ->
                System.out.println("DNA Sequence: " + dnaSequencer.getSequence());

        // Filter DNA sequences containing 'ATG'
        System.out.println("DNA Sequences containing 'ATG':");
        dnaSequencers.stream()
                .filter(atgSequenceFilter)
                .forEach(dnaSequencePrinter);

        // Convert DNA sequences to RNA sequences and print
        System.out.println("\nRNA Sequences:");
        dnaSequencers.stream()
                .map(dnaToRnaConverter)
                .forEach(System.out::println);
    }
}
