package java_fundamentals.java_basics.lambdas_11;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Predicate;
import java.util.function.Supplier;

// Protein interface representing a protein
interface Protein {
    String getSequence();
}

// Example class implementing the Protein interface
class ProteinBinder implements Protein {
    private String sequence;

    public ProteinBinder(String sequence) {
        this.sequence = sequence;
    }

    @Override
    public String getSequence() {
        return sequence;
    }
}

public class HighThroughputProteinBindingExample {
    public static void main(String[] args) {
        // Define a supplier to generate random protein sequences
        Supplier<String> proteinSequenceSupplier = () -> {
            StringBuilder proteinSequenceBuilder = new StringBuilder();
            for (int i = 0; i < 10; i++) {
                int aminoAcidIndex = (int) (Math.random() * 20);
                char aminoAcid = (char) ('A' + aminoAcidIndex);
                proteinSequenceBuilder.append(aminoAcid);
            }
            return proteinSequenceBuilder.toString();
        };

        // Create a list of protein binders representing protein sequences generated by the supplier
        List<Protein> proteinBinders = new ArrayList<>();
        for (int i = 0; i < 5; i++) {
            proteinBinders.add(new ProteinBinder(proteinSequenceSupplier.get()));
        }

        // Define a predicate to filter protein sequences containing 'ABC' sequence
        Predicate<Protein> abcSequenceFilter = protein -> protein.getSequence().contains("ABC");

        // Define a function to convert protein sequences to lowercase
        Function<Protein, String> proteinToLowercaseConverter = protein -> protein.getSequence().toLowerCase();

        // Define a consumer to print protein sequences
        Consumer<Protein> proteinSequencePrinter = protein ->
                System.out.println("Protein Sequence: " + protein.getSequence());

        // Filter protein sequences containing 'ABC'
        System.out.println("Protein Sequences containing 'ABC':");
        proteinBinders.stream()
                .filter(abcSequenceFilter)
                .forEach(proteinSequencePrinter);

        // Convert protein sequences to lowercase and print
        System.out.println("\nLowercase Protein Sequences:");
        proteinBinders.stream()
                .map(proteinToLowercaseConverter)
                .forEach(System.out::println);
    }
}
